name: Test CLI

on:
  push:
    paths:
      - '.github/**'
      - 'src/**'
      - 'test/**'
      - 'Makefile'
      - 'package-lock.json'
      - 'tsconfig.json'

jobs:
  test:
    name: cli-test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: npm i
      - run: make test
